export const API = {
    AUTH: {
        REGISTER: "/api/v1/auth/register",
        LOGIN: "/api/v1/auth/login",
        WHOAMI: "/api/v1/auth/whoami",
        UPDATE: "/api/v1/auth/update",
        FORGOT_PASSWORD: "/api/v1/auth/forgot-password",
        RESET_PASSWORD: "/api/v1/auth/reset-password",
    },
    ADMIN: {
        USERS: "/api/v1/admin/users",
        SCHOOLS: "/api/v1/admin/schools",
        ANALYTICS: "/api/v1/admin/analytics",
        NOTIFICATIONS: "/api/v1/admin/notifications",
        INQUIRIES: "/api/v1/admin/inquiries",
        REVIEWS: "/api/v1/admin/reviews",
    },
    SCHOOLS: "/api/v1/schools",
    SCHOOL_CATEGORY_COUNTS: "/api/v1/schools/category-counts",
    FAVORITES: "/api/v1/favorites",
    NOTIFICATIONS: "/api/v1/notifications",
    INQUIRIES: "/api/v1/inquiries",
    RECOMMENDATIONS: "/api/v1/recommendations",
    REVIEWS: "/api/v1/reviews",
};